[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/gulbeneser"
  to = "/gulbeneser/index.html"
  status = 200

[[redirects]]
  from = "/gulbeneser/*"
  to = "/gulbeneser/index.html"
  status = 200

[[redirects]]
  from = "/furkanyonat"
  to = "/furkanyonat/index.html"
  status = 200

[[redirects]]
  from = "/furkanyonat/*"
  to = "/furkanyonat/index.html"
  status = 200

[[redirects]]
  from = "/kariyer"
  to = "/kariyer/index.html"
  status = 200

[[redirects]]
  from = "/kariyer/*"
  to = "/kariyer/index.html"
  status = 200

[[redirects]]
  from = "/projects/:project"
  to = "/projects/:project/index.html"
  status = 200

[[redirects]]
  from = "/projects/:project/*"
  to = "/projects/:project/index.html"
  status = 200

[[redirects]]
  from = "/projeler/:project"
  to = "/projeler/:project/index.html"
  status = 200

[[redirects]]
  from = "/projeler/:project/*"
  to = "/projeler/:project/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
