[build]
  command = "npm run build"
  publish = "public"

[functions]
  directory = "netlify/functions"

[build.environment]
  TZ = "Europe/Istanbul"

[[redirects]]
  from = "/gulbeneser/assets/*"
  to = "/gulbeneser/assets/:splat"
  status = 200

[[redirects]]
  from = "/gulbeneser"
  to = "/gulbeneser/index.html"
  status = 200

[[redirects]]
  from = "/gulbeneser/*"
  to = "/gulbeneser/index.html"
  status = 200

[[redirects]]
  from = "/furkanyonat"
  to = "/furkanyonat/index.html"
  status = 200

[[redirects]]
  from = "/furkanyonat/assets/*"
  to = "/furkanyonat/assets/:splat"
  status = 200

[[redirects]]
  from = "/furkanyonat/*"
  to = "/furkanyonat/index.html"
  status = 200

[[redirects]]
  from = "/kariyer"
  to = "/kariyer/index.html"
  status = 200

[[redirects]]
  from = "/kariyer/assets/*"
  to = "/kariyer/assets/:splat"
  status = 200

[[redirects]]
  from = "/kariyer/*"
  to = "/kariyer/index.html"
  status = 200

[[redirects]]
  from = "/kariyer.html"
  to = "/kariyer/index.html"
  status = 200

[[redirects]]
  from = "/aboutcyprus/assets/*"
  to = "/aboutcyprus/assets/:splat"
  status = 200

[[redirects]]
  from = "/aboutcyprus"
  to = "/aboutcyprus/index.html"
  status = 200

[[redirects]]
  from = "/aboutcyprus/*"
  to = "/aboutcyprus/index.html"
  status = 200

[[redirects]]
  from = "/travel/assets/*"
  to = "/travel/assets/:splat"
  status = 200

[[redirects]]
  from = "/travel"
  to = "/travel/index.html"
  status = 200

[[redirects]]
  from = "/travel/*"
  to = "/travel/index.html"
  status = 200

[[redirects]]
  from = "/projects/:project"
  to = "/projects/:project/index.html"
  status = 200

[[redirects]]
  from = "/projects/:project/*"
  to = "/projects/:project/index.html"
  status = 200

[[redirects]]
  from = "/projeler/:project"
  to = "/projeler/:project/index.html"
  status = 200

[[redirects]]
  from = "/projeler/:project/*"
  to = "/projeler/:project/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
